FROM mysql:8.0

RUN { \
        echo '[client]'; \
        echo 'default-character-set=utf8'; \
        echo '[mysql]'; \
        echo 'default-character-set=utf8'; \
        echo '[mysqldump]'; \
        echo 'default-character-set=utf8'; \
        echo '[mysqld]'; \
        echo 'character-set-server=utf8'; \
    } >> /etc/mysql/conf.d/my.cnf 

WORKDIR /src 